language: node_js
node_js:
  - stable
addons:
    code_climate:
        repo_token: 5452c724dcf8b4dfa41af264941feb2afdbd01e965e5ce66b413fbef9b4fbe72
script: npm run test:cov
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info